### ISSUE TITLE
Plotting of IAGA-2002 files not working on Achim's PC

### ISSUE THREAD

**Issue by SimonFlower** [INTERMAGNET/DataCheck1s#4]
When trying to plot from the data checking dialog on Achim's PC (which plots IAGA-2002 data) the autoplot software installs successfully and starts, but an incorrect path is passed from DataCheck1s to Autplot, so the data is not displayed.

**Comment by SimonFlower** [comment]
I've added a new command line option to DataCheck1s:
  --debug-ap-comms
When this option is used the network communication between DataCheck1s and Autoplot will be printed on stdout. On my Windows PC here's what that looks like for a plot of the test data (select 'plot' radio button then double click on first "Filtered second - minute differences over threshold of 5.0 nT or 1.0 min. arc":

Autoplot: sending data [import startup as geomag]
Autoplot: received data [import startup as geomag]
Autoplot: sending data [reset ()]
Autoplot: received data [reset ()]
Autoplot: sending data [plot (0,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field3&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-10800.0&validMax=21600.0&title=Geomagnetic observatory data for Test (TST)&label=D(Minutes of arc)&units=Minutes of arc')]
Autoplot: received data [plot (0,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field3&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-10800.0&validMax=21600.0&title=Geomagnetic observatory data for Test (TST)&label=D(Minutes of arc)&units=Minutes of arc')]
Autoplot: sending data [dom.plots[0].controller.plot.xaxis.setVisible (0)]
Autoplot: received data [dom.plots[0].controller.plot.xaxis.setVisible (0)]
Autoplot: sending data [plot (1,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field4&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-88887.0&validMax=88887.0&label=H(nT)&units=nT')]
Autoplot: received data [plot (1,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field4&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-88887.0&validMax=88887.0&label=H(nT)&units=nT')]
Autoplot: sending data [dom.plots[1].controller.plot.xaxis.setVisible (0)]
Autoplot: received data [dom.plots[1].controller.plot.xaxis.setVisible (0)]
Autoplot: sending data [plot (2,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field5&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-88887.0&validMax=88887.0&label=Z(nT)&units=nT')]
Autoplot: received data [plot (2,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field5&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=-88887.0&validMax=88887.0&label=Z(nT)&units=nT')]
Autoplot: sending data [dom.plots[2].controller.plot.xaxis.setVisible (0)]
Autoplot: received data [dom.plots[2].controller.plot.xaxis.setVisible (0)]
Autoplot: sending data [plot (3,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field6&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=0.0&validMax=88887.0&label=F(nT)&units=nT')]
Autoplot: received data [plot (3,'vap+dat:file:/C:/data/DataCheck1sTestData/tst20140205dsec.sec?skipLines=28&time=field0&column=field6&timeFormat=$Y-$m-$d+$H:$M:$S.$(milli)&fill=99999.0&validMin=0.0&validMax=88887.0&label=F(nT)&units=nT')]
Autoplot: sending data [dom.plots[0].controller.row.top = '+2.0em']
Autoplot: received data [dom.plots[0].controller.row.top = '+2.0em']
Autoplot: sending data [dom.plots[0].controller.row.bottom = '28.90%-1.0em']
Autoplot: received data [dom.plots[0].controller.row.bottom = '28.90%-1.0em']
Autoplot: sending data [dom.plots[1].controller.row.top = '28.90%']
Autoplot: received data [dom.plots[1].controller.row.top = '28.90%']
Autoplot: sending data [dom.plots[1].controller.row.bottom = '55.80%-1.0em']
Autoplot: received data [dom.plots[1].controller.row.bottom = '55.80%-1.0em']
Autoplot: sending data [dom.plots[2].controller.row.top = '55.80%']
Autoplot: received data [dom.plots[2].controller.row.top = '55.80%']
Autoplot: sending data [dom.plots[2].controller.row.bottom = '81.00%-1.0em']
Autoplot: received data [dom.plots[2].controller.row.bottom = '81.00%-1.0em']
Autoplot: sending data [dom.plots[3].controller.row.top = '81.00%']
Autoplot: received data [dom.plots[3].controller.row.top = '81.00%']
Autoplot: sending data [dom.plots[3].controller.row.bottom = '112.30%-4.2em']
Autoplot: received data [dom.plots[3].controller.row.bottom = '112.30%-4.2em']

**Comment by sputnik-a** [comment]
The problem was the leading '/' in Linux absolute paths. They lead to invalid URI's of the kind:

_vap+dat:file://home/user/INTERMAGNET/dev/testdata/tst20140217dsec.sec_

whereas

_vap+dat:file:/home/user/INTERMAGNET/dev/testdata/tst20140217dsec.sec_

would be correct.

The error was fixed by using JAVA's toURI() method of class File, and was tested on Ubuntu Linux and Windows 7 running in VirtualBox   (https://github.com/INTERMAGNET/lib_bgs/commit/3c8bc1e1b0ae0b9313bb1e314ed31d6946462bdf)

Note that the method _public AutoplotURIBuilder (URIType uri_type, File file, String timerange)_ had to be modified as well, but the modification is NOT tested and the method is never called.
